### ISSUE TITLE
this.string is not a function

### ISSUE THREAD

**Issue by dpo** [hesstobi/atom-autocomplete-latex-cite#7]
I just installed this package and immediately received the message
```
Unable to parse Bibtex file /Users/dpo/tex/reports/working/sqd-ssy-overleaf/sqd-ssy.bib. It will be ignored for autocompletion. (this.string is not a function)
```
My BibTeX file defines several `@string`s.

The only occurence of `this.string` in the code is [here](https://github.com/hesstobi/atom-autocomplete-latex-cite/blob/5ce5ad3b292337fc5035508fd6fb88e71e70d53b/lib/lite-bibtex-parse.js#L349). I don't see any method named `string`. Is there a typo? Or something missing?

**Comment by hesstobi** [comment]
Yes, it looks like something is missing here. Can you post a short bib file example for testing?

**Comment by hesstobi** [comment]
This should be fixed now with the current version

**Comment by dpo** [comment]
I still get the same error with a bib file that contains `@string`s.

**Comment by hesstobi** [comment]
Ah sorry, version 0.3.2 will work, forgot that Atom is not collects the packages from github
